services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: carpooling
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - carpooling-db:/var/lib/postgresql/data

volumes:
  carpooling-db:
