spring.application.name=CarPooling

# TODO: add those from some secret store or environment variable
# TODO: do not EVER commit production password to GIT !!!
spring.datasource.url=jdbc:postgresql://localhost:5432/carpooling
spring.datasource.username=test
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=none


# Geonorge Address API url
carpooling.integrations.geonorge.url=https://ws.geonorge.no/adresser/v1/

#JWT Secret KEY
carpooling.authentication.jwt.key=PARSE_SECRET_HERE_MINIMUM_32_CHARACTERS
# JWT Expiration Time
carpooling.authentication.jwt.expiration=3600000