spring.application.name=CarPooling

spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=test
spring.datasource.password=test
spring.jpa.hibernate.ddl-auto=none

spring.flyway.url=jdbc:postgresql://localhost:5432/testdb
spring.flyway.user=test
spring.flyway.password=test
spring.flyway.locations=classpath:db/migration