### Register User Test
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "customUser",
  "email": "customUser@test.com",
  "hashedPassword": "customUsersPassword"
}

### Login Test
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=customUser&password=customUsersPassword

### Access Restricted Site Test
GET http://localhost:8080/users
Authorization: Bearer BEARERTOKEN_FROM_RESPONSE_ABOVE